language:
  node_js
node_js:
  - 12
before_install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - jest --ci --coverage && codecov
